pre-rebase-hook: runGitRebase: Handle 2.25.1 (#166)
Git uses patch versions, and our CI actually has a machine with git 2.25.1. Need to make sure it is handled correctly.

diff --git a/scripts/pre-rebase-hook/test-common b/scripts/pre-rebase-hook/test-common
--- a/scripts/pre-rebase-hook/test-common
+++ b/scripts/pre-rebase-hook/test-common
@@ -120,29 +120,23 @@ cleanupSandbox() {
 runGitRebase() {
   local -a args=( "$@" )
 
-  # Our CI is running a very old version of git that does not have a `merge` backend.  And so it
-  # does not support some of the flags.  At the same time, I want to be able to re-apply commits
-  # that where applied previously.  After we upgrade our CI, we can remove this block.
-  #
-  # === Remove after CI upgraded post git 2.25 { ===
-  local gitVersion
-  gitVersion=$(git --version)
-  gitVersion=${gitVersion#git version }
-
-  # Check if current version is at or before 2.25, by checking if it sorts before 2.25.
-  #
-  if printf '%s\n2.25\n' "$gitVersion" | sort -C -V; then
-    # As 2.25 uses `apply` backend for merging, it is as if `--reapply-cherry-picks` is already in
-    # effect.  So we can just remove it.
-    local -a newArgs
+  if ! gitSupportsMergeBackend; then
+    local -a applyBackendArgs
     for arg in "${args[@]}"; do
-      if [[ "$arg" != "--reapply-cherry-picks" ]]; then
-        newArgs+=("$arg")
-      fi
+      case "$arg" in
+        --reapply-cherry-picks)
+          # `apply` backend is operates as if `--reapply-cherry-picks` is always on, and does not
+          # support the flag.  For the current uses of `runGitRebase` we can just skip this flag and
+          # have identical behavior between both backends.
+          ;;
+
+        *)
+          applyBackendArgs+=("$arg")
+          ;;
+      esac
     done
-    args=("${newArgs[@]}")
+    args=("${applyBackendArgs[@]}")
   fi
-  # === Remove after CI upgraded post git 2.25 } ===
 
   local prevOps
   prevOps=$(set +o)
@@ -298,16 +292,8 @@ EOM
 
 # Verifies that `runGitRebase` was successful.
 #
+# This function is only necessary as long as we need to support git without the `merge` backend.
 # Takes expected success messages for both `apply` and `merge` git rebase backends.
-#
-# Our CI is running a 4 years old version of git :'(
-# 2.25 is the last version that does not have a modern `merge` backed for rebase.  It
-# uses an `apply` backend that outputs progress to stdout, instead of stderr.  So
-# checks for a successful rebase operation are different.
-#
-# See https://github.com/git/git/blob/master/Documentation/RelNotes/2.26.0.txt
-#
-# Remove this when CI machines are updated.
 assertSuccesfulRebase() {
   if [[ $# -ne 2 ]]; then
     echo "ERROR: assertSuccesfulRebase takes 2 arguments"
@@ -317,13 +303,7 @@ assertSuccesfulRebase() {
   local expectedApplyOutput=$1
   local expectedMergeOutput=$2
 
-  local gitVersion
-  gitVersion=$(git --version)
-  gitVersion=${gitVersion#git version }
-
-  # Check if current version is at or after 2.26, by checking if it sorts after 2.26.
-  #
-  if printf '2.26\n%s\n' "$gitVersion" | sort -C -V; then
+  if gitSupportsMergeBackend; then
     assertStdout ''
     assertStderr "$expectedMergeOutput"
   else
@@ -389,6 +369,30 @@ gitMockRemoteBranch() {
   local branchFile=".git/refs/remotes/$remote/$branch"
   mkdir -p "$(dirname "$branchFile")"
   printf "%s\n" "$commit" >"$branchFile"
+}
+
+# Returns a successful exit code if current `git` supports `merge` backend.
+#
+# `git rebase` behaves slightly differently depending on the backend used: `apply` or `merge`.
+# In particular, `git rebase` output messages are completely different depending on the backend.
+# It would be possible to just always use the newer `merge` backend, if our CI machines would not be
+# so old.  They use more than 4 year old Ubuntu distribution with git version 2.25 - the last one
+# that does not have the `merge` backend just yet.
+#
+# In a few cases we need to check if the output was generated by the `apply` or the `merge` backend
+# and perform different actions.
+#
+# See https://github.com/git/git/blob/master/Documentation/RelNotes/2.26.0.txt
+#
+# Remove this function and all the connected conditional code as soon as CI machines are updated.
+gitSupportsMergeBackend() {
+  local gitVersion
+  gitVersion=$(git --version)
+  gitVersion=${gitVersion#git version }
+
+  # We check by sorting the current git version after `2.26` - first version that comes with the
+  # `merge` backend.
+  printf '2.26\n%s\n' "$gitVersion" | sort -C -V
 }
 
 #
